# Generated by Django 6.0 on 2026-01-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_business_logo"),
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bill",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="bill",
            name="bill_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="bill",
            unique_together={("business", "bill_number")},
        ),
    ]
