# Generated by Django 6.0 on 2026-01-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_alter_bill_options_alter_bill_bill_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bill",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
