# Generated by Django 6.0 on 2026-01-01 19:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_bill_deleted_at_bill_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
