# Generated by Django 6.0 on 2026-01-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_alter_bill_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="bill_number",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
