# Generated by Django 6.0 on 2025-12-30 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="address",
        ),
        migrations.RemoveField(
            model_name="business",
            name="phone",
        ),
    ]
