# Generated by Django 6.0 on 2026-01-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="business_logos/"),
        ),
    ]
