# Generated by Django 6.0 on 2026-01-02 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_businessprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BusinessProfile",
        ),
    ]
