# Generated by Django 6.0 on 2026-01-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_delete_businessprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="upi_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
